language: cpp

os: linux
dist: bionic
sudo: required
name: Python 3.8, c++17 gcc 7
python: "3.8"
compiler: gcc
env: PYTHON=3.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - gfortran
      - python3.8-dev
      - python3.8-venv
      - trang

before_install:
  - pyenv global $(pyenv whence 2to3) # activate all python versions
  - PY_CMD=python3
  - $PY_CMD -m pip install --user --upgrade pip wheel setuptools
install:
  - $PY_CMD -m pip install --user --upgrade pytest
  - $PY_CMD -m pip install pytest-xdist
  - $PY_CMD -m pip install --user --upgrade lxml
  - $PY_CMD -m pip install --user --upgrade numpy
  - $PY_CMD -m pip install --user --upgrade matplotlib
script:
  - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
  - export CC=/usr/bin/gcc-7
  - export CXX=/usr/bin/g++-7
  - g++ -v
  - make -j
  - make examples
  - make unit-tests
  - make tests -j
